### ISSUE TITLE
Compiling pyqt5 project

### ISSUE THREAD

**Issue by stupid-kid-af** [niess/python-appimage#42]
Docs is very confusing.
Can you tell me how to compile pyqt5 projects/app to appimage.
Repo => https://github.com/ankydv/Dice-Simulator

Any help would be highly appreciated.

**Comment by niess** [comment]
Hello @stupid-kid-af,

examples of applications can be found in the [applictions](https://github.com/niess/python-appimage/tree/master/applications) folder. For example, the `tasmostizer` app uses PyQt5. However, these examples concern packages that are already available on PyPI.

My understanding is that your app is currently distributed via GitHub, by providing the source. Thus, I would first publish it on PyPI. You can find examples for this over the web, e.g. [over there](https://realpython.com/pypi-publish-python-package/). Then, you could copy and modify one of the sample AppImage applications data herein in order to build your own AppImage. But, note that once your application is published on PyPI, you might not need an AppImage anymore. Since then, users could `pip install Dice-Simulator`. The "benefit" of the AppImage is that it also packages the whole Python env, in case the user does not have it.

If you'd rather build an AppImage directly, without publishing on PyPI, then I would download a `manylinux2014` Python AppImage from the [releases](https://github.com/niess/python-appimage/releases), for example [python3.9.9-cp39-cp39-manylinux2014_x86_64.AppImage](https://github.com/niess/python-appimage/releases/download/python3.9/python3.9.9-cp39-cp39-manylinux2014_x86_64.AppImage), and I would modify it manually. Please refer to the [AppImage documentation](https://docs.appimage.org/packaging-guide/index.html) for more details in this case.

**Comment by stupid-kid-af** [comment]
@niess Will try
Btw thnx for replying
