### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gitUser000** [niess/python-appimage#54]
Hi, very very very good jobs...

Is it possible to add supports to tcl/tk v8.6 in "recent" (>= 3.6) appimages  ?
It would be very great. 

By the way thank for you work

**Comment by niess** [comment]
Hello @gitUser000,

thank you for pointing this out. The issue was that I hard-coded the search location for Tcl/Tk libraries, but the installation prefix (recently?) changed in manylinux Docker images. I updated `python-appimage` in order to locate Tcl/Tk path dynamically, using the corresponding host `tclsh` executable. This should be more robust in the future if the installation prefix changes again. Now the proper Tcl/Tk versions should be bundled in AppImages. Note that the bundled version of Tcl/Tk actually depends on the manylinux tag, not on the Python version. That is:

- manylinux1 => Tcl/Tk 8.4
-  manylinux2010 => Tcl/Tk 8.5
-  manylinux2014 => Tcl/Tk 8.6

Thus, if you use a manylinux2014 image, then you should have Tcl/Tk 8.6.

**Comment by gitUser000** [comment]
Hi, 
checked with python3.9.14-cp39-cp39-manylinux2014_x86_64.AppImage : OK
Many thanks for this very fast fix/update.

**Comment by niess** [comment]
Great. I am closing then.
