### ISSUE TITLE
xonsh AppImage is broken after Jun changes

### ISSUE THREAD

**Issue by anki-code** [niess/python-appimage#60]
Hi @niess!

We've noticed that xonsh.AppImage [0.12.4 (May 9)](https://github.com/xonsh/xonsh/releases/download/0.12.4/xonsh-x86_64.AppImage) is working but starting from xonsh release [0.12.5 (Jun 17)](https://github.com/xonsh/xonsh/releases/download/0.12.5/xonsh-x86_64.AppImage) it's not working.
Example:
```python
cd /tmp
wget https://github.com/xonsh/xonsh/releases/download/0.13.3/xonsh-x86_64.AppImage
chmod +x xonsh-x86_64.AppImage
./xonsh-x86_64.AppImage --no-rc
# Freez OR bash: warning: shell level (1000) too high, resetting to 1
```

I think some of [python-appimage commits in Jun 11-14](https://github.com/niess/python-appimage/commits/master) is the cause.

Could you please test the python-appimage with xonsh and give us the advice?
The building process is:
```python
mkdir -p /tmp/build && cd /tmp/build
git clone --depth 1 https://github.com/xonsh/xonsh
cd xonsh/appimage
echo 'xonsh' > requirements.txt
cat pre-requirements.txt >> requirements.txt  # here you can add your additional PyPi packages to pack them into AppImage
cd ..
pip install git+https://github.com/niess/python-appimage
python -m python_appimage build app --python-version 3.10 ./appimage
./xonsh-x86_64.AppImage
```

Thanks!

**Comment by niess** [comment]
Hey @anki-code,

Sorry for the issue. I Indeed did some updates lately. Unfortunately, it is complicated for me to test all application cases when I do so. But, I understand that your issue has been solved finally. Fortunately :)

Tracing back the reason for such issues might be complicated since there is no history of the Python AppImages themselves. Furthermore, PyPA might also update the base Manylinux Docker container ... which might also impact the Python AppImage.
