### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by pombredanne** [niess/python-appimage#62]
Hi!
Thanks for this project. We are considering using this as a based for AppImages for https://github.com/nexB/scancode-toolkit and a few other FOSS projects and I have a licensing question:

Your project code here is GPL-licensed alright, but do you consider the generated AppImages to be also subject to the GPL?
@jonoyang FYI

**Comment by niess** [comment]
Hello,

thank you for raising this point. I didn't think about it so far. Indeed, one has to distinguish

- **A**: the `python-appimage` application / Python package,
- **B**: the produced ManyLinux Python AppImages (i.e. using the `--manylinux` option).
- **C**: the produced Python based applications (i.e. using the `--app` option).

My, intent was to GPL only **A**. My understanding is that **B** and **C** depend on their software content. Thus, I would say that B is PSF licensed, and that **C** (which builds over **B**) should conform at least to PSF, as well as to any added software.

Now, there is some complication because **A** actually adds a few hooks to vanilla `CPython`, the like `sitecustomize.py`. Thus, there might be some ambiguity at that level. Yet, my intent is that **B** should still be PSF licensed.

Does this make sense?

**Comment by pombredanne** [comment]
@niess Thank you ++ for the detailed and clear explanation!
You wrote:

> Now, there is some complication because A actually adds a few hooks to vanilla CPython, the like sitecustomize.py. Thus, there might be some ambiguity at that level. Yet, my intent is that B should still be PSF licensed.

For sake of clarity, it would be awesome if these few hooks would be also PSF-licensed, so that things are 100% clear.

**Comment by niess** [comment]
@pombredanne, 

I have updated the license. In order to keep things simple, the files that get bundled in the AppImage (located under `python_appimage/data`) are now explicitly MIT licensed. Thus, the resulting AppImage should be GPL free (mostly PSF, except for AppImage-specific hooks &metadata that are MIT).

I also updated the README accordingly.

Does this work?

**Comment by pombredanne** [comment]
@niess you rock! Thank you ++ and happy new year! :tada:

**Comment by niess** [comment]
Happy new year :)

You're welcome.

Then, I am closing this.
