### ISSUE TITLE
Allow < and @ sign in requirements.txt

### ISSUE THREAD

**Issue by overbost** [niess/python-appimage#66]
Every line in requirements is injected in shell, if there are "<" or "<"= sign it break because "<" is special symbol in shell.

Before[ this line ](https://github.com/niess/python-appimage/blob/818fe273c124223ce651e3ba5d439de9a9550cd7/python_appimage/commands/build/app.py#L280) the line should be incorporated in apices like:

`"'{r}'".format(r=requirement)`

```
# not works
$ pip install package<=0.5
```

```
# works
$ pip install 'package<=0.5'
```

i temporary solved by adding apices in my requirements

EDIT
git repository with specific branch doesn't work, and putting apices doesn't solve. I must use main branch
```
# not works
git+https://github.com/overbost/myrepo@devbranch
```

**Comment by niess** [comment]
Hello @overbost ,

thank you for pointing this out. Implementing your proposal seems straightforward.  But, unfortunately, it does not seem to solve the second issue, which I do not quite understand.

I currently have little availability for this project. Since there is an easy solution (manually wrapping with ''), I'll leave this as so for now. But, I am open to a PR, if someone manages to solve both issues.

**Comment by dotzborro** [comment]
@overbost fyi git requirements are working now

related PR: https://github.com/niess/python-appimage/pull/73
