### ISSUE TITLE
python3.12 support/release

### ISSUE THREAD

**Issue by py-radicz** [niess/python-appimage#71]
Hey, is there some blocker to distribute also py3.12 version? or anything I can do to make it happen?

**Comment by niess** [comment]
Hello @py-radicz,

thank you for pointing this out. The issue was that I had to manually add new Python versions to the workflow matrix, in order to get the corresponding AppImages generated. I am in the process of rewriting this, using [pyGitHub](https://github.com/PyGithub/PyGithub) instead of gluing together different actions, available on the 'Market'. This provides more flexibility (but it is rather time-consuming).

Anyway, the new updater just released AppImages for Python 3.12 (see [releases](https://github.com/niess/python-appimage/releases/tag/python3.12)). I didn't test them though.

**Comment by py-radicz** [comment]
many thanks for fast turn around!
